version: '3.9'
services:
  tm_data:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TM_DATA_USERNAME
      - TM_DATA_PASSWORD
    restart: always
    volumes:
      - ./terraform/.terraformrc:/.terraformrc
      - ./terraform:/app/terraform
      - ./config:/app/config
